language: c
# safelist
os: linux
arch: amd64
branches:
  only:
  - master
script: ./configure --with-restconf=fcgi && make && sudo make install && make test
before_script:
  - sudo apt-get install -y libfcgi-dev
#  - if [[ -n "${DOCKERUSER}" ]]; then echo "$DOCKERPASSWD" | docker login -u "$DOCKERUSER" --password-stdin; fi
  - echo "$DOCKERPASSWD" | docker login -u "$DOCKERUSER" --password-stdin
  - ./test/travis/before_script.sh
