name: Clixon CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
# 1) checkout and compile natively
    - name: install cligen
      run: (git clone https://github.com/clicon/cligen.git && cd cligen && ./configure && make && sudo make install)
    - name: install dependencies
      run: sudo apt install -y libssl-dev libnghttp2-dev curl-dev
    - name: configure
      run: ./configure
# 2) Use docker for tests
    - name: make test # this is docker test
      run: make test
